# Database
spring.datasource.url=jdbc:mysql://localhost:3306/ciaklog_db
spring.datasource.username=root
spring.datasource.password=

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# JWT
jwt.secret=ALMENO_32_CARATTERI_METTINE_UNA_LUNGA_E_CASUALE
jwt.expiration=86400000

# TMDB
tmdb.api.key=004275e8376e1706e0620cbe7fba9e5b

# Gemini
gemini.api.key=CHIAVE_GEMINI