spring.application.name=ciaklog

spring.datasource.url=jdbc:mysql://localhost:3306/ciaklog_db
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=chiave-segreta-lunga-almeno-32-caratteri
jwt.expiration=86400000
tmdb.api.key=ae65373fc4d3d8e9dd02de5ca375c9f7
ai.api.key=AQ.Ab8RN6Kk5qKvaJE04gS3Uq-5VKTxfS_dZ376UctmY3gLNT5Q8w